### ISSUE TITLE
command not found: jrm

### ISSUE THREAD

**Issue by poponuts** [bhovhannes/junit-report-merger#69]
I installed this package on my cypress test automation root directory:
`npm i --save-dev junit-report-merger`

It subsequently created a dev dependency on my `package.json` file:
```
"devDependencies": {
    "junit-report-merger": "^2.0.0"
}
```

However, running the next cli command: `jrm ./cypress/test-reports/combined.xml "./cypress/test-reports/junit*.xml"` generates the error: `zsh: command not found: jrm`

It seems the jrm binary wasn't created.

OS: MacOS Big Sur

**Comment by bhovhannes** [comment]
I guess this is because you installed `junit-report-merger` locally. In
that case `jrm` binary is available only to npm or Yarn.
So, the best approach in this case will be adding a script to the `scripts`
section of the package.json, which will contain your command. Then in your
ci run that script with `npm run ... ` or `yarn ... `.

Another approach would be installing `junit-report-merger` globally with
`npm i  g junit-report-merger`. In that case `jrm` binary will be available
globally.

**Comment by bhovhannes** [comment]
I guess this is because you installed `junit-report-merger` locally. In
that case `jrm` binary is available only to npm or Yarn.
So, the best approach in this case will be adding a script to the `scripts`
section of the package.json, which will contain your command. Then in your
ci run that script with `npm run ... ` or `yarn ... `.

Another approach would be installing `junit-report-merger` globally with
`npm i  g junit-report-merger`. In that case `jrm` binary will be available
globally.

**Comment by bhovhannes** [comment]
I've added that info to Readme to avoid future confusions.Let me know if instructions worked for you.

**Comment by poponuts** [comment]
Thanks. Appreciate your swift response. Yes, it definitely did!
