### ISSUE TITLE
creates empty xml report

### ISSUE THREAD

**Issue by s-kugan** [bhovhannes/junit-report-merger#71]
Hi,

when I run the command in CLI , It is not returning any error but it is creating an empty xml file with the given name. any help is much appreciated.

**Comment by bhovhannes** [comment]
Hi,

empty xml report is created when `jrm` does not find any files to merge.

I will add more diagnostic output to the cli to make it more clear. That will be a good improvement, thanks! 

Before that I recommend to check if your glob pattern is correct and actually matches files.

**Comment by s-kugan** [comment]
Hi,

Thank you for the response. This is the command i am running in CLI which generates empty xml report. `jrm ./combinedresults/xml_reports/part1.xml "./reports/*.xml"` .  The reports directory has more than one sub-directories and each sub-directories has each xml file report.  If you can give a feed-back for this command. it will be grateful regarding the global pattern.

**Comment by bhovhannes** [comment]
> Thank you for the response. This is the command i was running in CLI which was generating empty xml report. jrm ./combinedresults/xml_reports/part1.xml "./reports/*.xml" . The reports directory has more than one sub-directories and each sub-directories has each xml file report. I have figured out and as u said the issue was due to incorrect global pattern. I have included ** to include sub-directories now its working. jrm ./combinedresults/xml_reports/part1.xml "./reports//**/*.xml"

Glad you figured it out. So, I am closing this issue.

> My actual question is , I have installed this module globally and if i installed this module locally and then run the command, its returning jrm : The term 'jrm' is not recognized as the name of a cmdlet, function, script file, or operable program. I believe i have to set the path for this. I am using VS Code. How do i set path locally for this module ?

`junit-report-merger` does not differ from any `npm` package which provides a cli. Its `jrm` binary is resolved by standard `npm` way.

When you install `junit-report-merger` globally, with `npm install -g junit-report-merger`, `npm` adds the 'binary' to the `PATH`, which means you can call `jrm` from any folder on your system.
When you install `junit-report-merger`locally, usually by adding it to your package.json and doing `npm install`, `npm` does not change system `PATH`. Thus, to run `jrm` you should add a script to `package.json`, and later run that script with `npm run <script_name>`. `npm run` [adds `./node_modules/.bin` folder to system `PATH`](https://docs.npmjs.com/cli/v6/commands/npm-run-script), that's why that works.
